---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keitaro-charts
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://keitaro-charts.storage.googleapis.com
