---
apiVersion: v1
kind: Namespace
metadata:
  name: ckan
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keitaro-charts
  namespace: ckan
spec:
  interval: 1m0s
  url: https://git.schuurman-it.com/api/packages/packages/helm

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ckan-source-folder
  namespace: ckan
spec:
  interval: 10m0s
  path: ./apps/ckan
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
