---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-source
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
