---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ckan
  namespace: ckan
spec:
  chart:
    spec:
      chart: ckan
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: schuurman-it
  interval: 1m0s
