---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ckan
  namespace: ckan
spec:
  chart:
    spec:
      chart: ckan
      reconcileStrategy: ChartVersion
      install:
        createNamespace: true
      sourceRef:
        kind: HelmRepository
        name: keitaro-charts
  interval: 1m0s
